name: Lint and Test Snakemake workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint_and_test:
    name: Lint and test workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.6.0
        with:
          directory: "."
          snakefile: "main.smk"
          args: "--lint --configfile test.cfg"
          #- name: Testing
          #  uses: snakemake/snakemake-github-action@v1.6.0
          #  with:
          #    directory: "."
          #    snakefile: "main.smk"
          #    args: "--cores 1 --configfile test.cfg --use-singularity"
